import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
import { commerceApi } from "./commerce-api";

export type StorefrontConfig = { storeName:string; legalName:string; businessGstin:string; businessAddress:string; logoUrl:string; faviconUrl:string; primaryColor:string; accentColor:string; backgroundColor:string; currency:string; locale:string; supportEmail:string; supportPhone:string; announcement:string; footerTagline:string; seoTitle:string; seoDescription:string; primaryDomain:string };
export const defaultStorefrontConfig:StorefrontConfig={storeName:"Aster & Row",legalName:"Aster & Row",businessGstin:"",businessAddress:"",logoUrl:"",faviconUrl:"",primaryColor:"#18201d",accentColor:"#a85132",backgroundColor:"#f5f2eb",currency:"INR",locale:"en-IN",supportEmail:"support@asterandrow.example",supportPhone:"",announcement:"Complimentary shipping above ₹5,000",footerTagline:"Considered goods for everyday living.",seoTitle:"Aster & Row",seoDescription:"Considered goods for everyday living.",primaryDomain:""};
const StorefrontContext=createContext(defaultStorefrontConfig);
export function StorefrontProvider({children}:{children:ReactNode}){const [config,setConfig]=useState(defaultStorefrontConfig);useEffect(()=>{commerceApi<StorefrontConfig>("/api/v1/storefront/config").then(value=>{setConfig(value);const root=document.documentElement;root.style.setProperty("--store-primary",value.primaryColor);root.style.setProperty("--store-accent",value.accentColor);root.style.setProperty("--store-background",value.backgroundColor);document.title=value.seoTitle||value.storeName;root.lang=value.locale;if(value.faviconUrl)document.querySelector<HTMLLinkElement>('link[rel="icon"]')?.setAttribute("href",value.faviconUrl)}).catch(()=>undefined)},[]);return <StorefrontContext.Provider value={config}>{children}</StorefrontContext.Provider>}
export const useStorefrontConfig=()=>useContext(StorefrontContext);
export function StoreBrand(){const config=useStorefrontConfig(),initials=config.storeName.split(/\s+/).map(part=>part[0]).join("").slice(0,2).toUpperCase();return <a href="/" className="brand">{config.logoUrl?<img src={config.logoUrl} alt={config.storeName}/>:<i>{initials}</i>}<span>{config.storeName}</span></a>}
